### ISSUE TITLE
test_file_ffi.lua:148: assertion failed!

### ISSUE THREAD

**Issue by xiaoxuanzi** [baishancloud/lua-std-ffi#3]
I use luajit to run test  and found a error . 
The test_name is  test_data_sync.

`luajit: test_file_ffi.lua:148: assertion failed!
stack traceback:
	[C]: in function 'assert'
	test_file_ffi.lua:148: in function 'test_open_time'
	test_file_ffi.lua:451: in main chunk
	[C]: at 0x00404180`

Also in function test_write_sync：

`luajit: test_file_ffi.lua:321: assertion failed!
stack traceback:
	[C]: in function 'assert'
	test_file_ffi.lua:321: in function 'test_write_sync'
	test_file_ffi.lua:456: in main chunk
	[C]: at 0x00404180
`
Is there anything wrong?
Thanks,

**Comment by drmingdrmer** [comment]
Please provide more information thus we can reproduce this issue more easily:

What OS were you using when running these test?
What is the version of your lua language?

**Comment by chuang0721** [comment]
To test sync api, I calculate the sync api consume time, and identify it whether in expected range.
So the problem you encounter is that sync time is not in the expected range.
The machine performance is different， maybe the sync api you called is too slow or too fast.
I will expand the range，let this case in most machines to pass .

**Comment by xiaoxuanzi** [comment]
Sorry for the delayed response.
Host is Virtual Machine
$lsb_release -a

LSB Version:	:base-4.0-amd64:base-4.0-noarch:core-4.0-amd64:core-4.0-noarch:graphics-4.0-amd64:graphics-4.0-noarch:printing-4.0-amd64:printing-4.0-noarch
Distributor ID:	RedHatEnterpriseServer
Description:	Red Hat Enterprise Linux Server release 6.7 (Santiago)
Release:	6.7
Codename:	Santiago

$ luajit -v
LuaJIT 2.0.4 -- Copyright (C) 2005-2015 Mike Pall. http://luajit.org/

**Comment by drmingdrmer** [comment]
@chuang0721 

It'd be better if split this assertion to two. It would be more clear about which condition is unsatisfied.
```
 assert(min_tm <= use_tm and use_tm < max_tm)
```

**Comment by chuang0721** [comment]
@drmingdrmer  OK

**Comment by chuang0721** [comment]
@xiaoxuanzi  I have extended the range, you can try again.

**Comment by xiaoxuanzi** [comment]
@chuang0721 
the same problem:

$luajit test_file_ffi.lua 
test_create	 OK
test_readonly	 OK
test_writeonly	 OK
test_readwrite	 OK
test_trunc	 OK
test_append	 OK
min_tm:	0	use_tm:	0
test_nosync	 OK
min_tm:	0	use_tm:	0
test_noblock	 OK
min_tm:	1	use_tm:	0
luajit: test_file_ffi.lua:148: assertion failed!
stack traceback:
	[C]: in function 'assert'
	test_file_ffi.lua:148: in function 'test_open_time'
	test_file_ffi.lua:453: in main chunk
	[C]: at 0x00404180

I add print('min_tm:', min_tm, 'use_tm:', use_tm)  in  test_file_ffi.lua

**Comment by chuang0721** [comment]
Maybe your machine is too fast.
I increase test data size,
Could you try again? 
Thank you.

**Comment by xiaoxuanzi** [comment]
@chuang0721 
Unfortunately, the problem occur again!
My machine is too fast? it's just a VM.
And i do not understand why you set min_tm equal 1 in test_data_sync.

$luajit test_file_ffi.lua 
test_create	 OK
test_readonly	 OK
test_writeonly	 OK
test_readwrite	 OK
test_trunc	 OK
test_append	 OK
test_nosync	 OK
test_noblock	 OK
luajit: test_file_ffi.lua:150: assertion failed!
stack traceback:
	[C]: in function 'assert'
	test_file_ffi.lua:150: in function 'test_open_time'
	test_file_ffi.lua:455: in main chunk
	[C]: at 0x00404180

**Comment by xiaoxuanzi** [comment]
@chuang0721 ,you are right.
The problem arises because of my VM is very fast.
The number of sectors  written to the device per second is 100M.

thx
